import subprocess


# We run the spiders to populate the database
print("Running spiders...")
print("Starting with Buscojobs...")
subprocess.run(["bash", "-c", "scrapy crawl buscojoblistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl buscojobpostspider"])
print("Buscojobs finished")
print("Starting with Chiletrabajo...")
subprocess.run(["bash", "-c", "scrapy crawl chiletrabajolistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl chiletrabajopostspider"])
print("Chiletrabajo finished")
print("Starting with Computrabajo...")
subprocess.run(["bash", "-c", "scrapy crawl computrabajolistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl computrabajopostspider"])
print("Computrabajo finished")
print("Starting with Laborum...")
subprocess.run(["bash", "-c", "scrapy crawl laborumlistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl laborumpostspider"])
print("Laborum finished")
print("Starting with Trabajando...")
subprocess.run(["bash", "-c", "scrapy crawl trabajandolistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl trabajandopostspider"])
print("Trabajando finished")
print("Starting with Estado...")
subprocess.run(["bash", "-c", "scrapy crawl estadolistingspider"])
subprocess.run(["bash", "-c", "scrapy crawl estadopostspider"])
print("Estado finished")
